spring:
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener
    username: ${dbusername}
    password: ${dbpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
